### ISSUE TITLE
async coroutine vs generator

### ISSUE THREAD

**Issue by DiscordLiz** [mikeshardmind/lumi#8]
https://discuss.python.org/t/overloads-of-async-generators-inconsistent-coroutine-wrapping/56665/6

Hoping you agree with me on this, and that when describing Python functions to use from Lumi this will be okay.

**Comment by mikeshardmind** [comment]
Uhh, no not exactly. You can blame people overloading things into Coroutine objects for why not, can elaborate more over discord or here later.

**Comment by DiscordLiz** [comment]
Oh. I was misunderstanding. Who thought auto wrapping that was a good idea? Did they design it without considering stubs at all?
